# Generated by Django 4.1.1 on 2022-09-17 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80)),
                ('sobre', models.CharField(max_length=200)),
                ('conteudo', models.TextField()),
                ('categoria', models.TextField()),
                ('observacoes', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('data_publicacao', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
